[package]
name = "rust-image-test"
version = "0.1.0"
authors = ["KatsuNakajima <40666782+katsuNakajima@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"
